### ISSUE TITLE
You can add your project to Awesome-PicGo~

### ISSUE THREAD

**Issue by Molunerfinn** [jwenjian/giki-cli#1]
Thank you for choosing picgo! You can add your project to Awesome-PicGo~:

https://github.com/PicGo/Awesome-PicGo

**Comment by jwenjian** [comment]
> Thank you for choosing picgo! You can add your project to Awesome-PicGo~:
> 
> https://github.com/PicGo/Awesome-PicGo

PR created.

**Comment by Molunerfinn** [comment]
Nice!
