### ISSUE TITLE
大佬 请问AHK如何调用cmder，并执行命令 picgo u

### ISSUE THREAD

**Issue by zbb7001** [jwenjian/giki-cli#21]
> 最好能在选中文件的情况下，先执行复制，再执行上传命令 。
##  我以前用picgo-core的这条命令  Run, cmd /c "picgo u"  ，上传剪贴板中的截图及文件都没问题，但最近几天只能上传截图，文件无法上传了， 如果我打开cmder,  并输入  picgo u    一切都正常，无论上传什么，看到你写的代码，就冒昧地进来请教了，请原谅。

**Comment by jwenjian** [comment]
抱歉, 对 AHK 不熟悉, 不过感觉起来是 picgo core 的问题?, 可以去 [这里](https://github.com/PicGo/PicGo-Core) 问下看看.
